l_german:
########################################################
### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ###
########################################################

#changed to British spelling
 PRODUCTION_MATERIALS_ALUMINIUM: "Aluminium"
 PRODUCTION_VEHICLES_BUTTON: "Panzer bauen"
 PRODUCTION_VEHICLES_BUTTON_DISABLED: "Gepanzerte Fahrzeuge wurden noch §Rnicht erfunden§!!"
 PRODUCTION_ARMOR_FILTER: "Panzer"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE: "§HLizenzproduktion§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL: "§HLizenzproduktionausstoß§!\nGesamt: $VALUE|+%$\nAufteilung:"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION: "§YLizenz-Technologieunterschied§!:\n Basis: $BASE|+%$\n Modifiziert gesamt: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER: "§YLizenzmodifikator§!:\n Basis: $BASE|+%$\n Modifiziert gesamt: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION: "§YNicht in Bündnis mit Lizenzgeber§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE: "§YKeine aktive Lizenz§!: $VALUE|+%$"
 LICENSED_PURCHASE_CIC_COST: "§YDiese Lizenz kostet§!: £civ_factory $AMOUNT|Y$"
